FTPCOMMAND.MODULE: FTPCOMMAND.CLLE
FTPIN.MODULE: private PRECMD := CRTSRCPF FILE(FTPCMD) RCDLEN(112)
FTPIN.MODULE: FTPIN.RPGLE
FTPIN.MODULE: private POSTCMD := DLTF FILE(FTPCMD)
FTPSRV.SRVPGM: FTPSRV.BND FTPIN.MODULE FTPCOMMAND.MODULE
SERVICES.BNDDIR: SERVICES.BNDDIR FTPSRV.SRVPGM